# Generated by Django 5.0.1 on 2024-01-22 01:35

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                null=True, upload_to=social_media.models.profile_image_file_path
            ),
        ),
    ]
