# Generated by Django 5.0.1 on 2024-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="social_media.profile"
            ),
        ),
    ]
