# Generated by Django 5.0.1 on 2024-01-22 14:02

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0004_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social_media.models.post_image_file_path,
            ),
        ),
    ]
